# Generated by Django 3.2.6 on 2021-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('serviceAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
