# Generated by Django 3.2.6 on 2021-08-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
