# Generated by Django 3.2.6 on 2021-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(default='person', max_length=255),
        ),
    ]
